n = int(input())
m = int(input())
fdn = n // 10
ldn = n % 10
fdm = m // 10
ldm = m % 10
x1 = max(fdn, ldn, fdm, ldm)
x3 = min(fdn, ldn, fdm, ldm)
x2 = fdn + ldn + fdm + ldm - x1 - x3
if x2 >= 10:
    x2 = x2 % 10
print(x1, x2, x3, sep='')
